IconButton 컴포넌트 추가
plants-studio/plants-ui pull request #13
Opened 2020-11-26 10:28 UTC by xodus0721

src/Button/ 아래에 IconButton.tsx 파일을 추가했습니다.

2020-11-26 13:39 UTC, plantstoen requested changes

2020-11-26 13:39 UTC, plantstoen commented on src/button/basic-button/Button.stories.tsx
> +      <Button themeType="primary">
여기서 왜 <Button>을 <Button themeType="primary"> 로 바꾼 이유가 있을까요?? 어차피 Button.tsx에서 Button.defaultProps 대신 props를 받아오는 부분에서 기본값을 primary로 한거같은데, 혹시 지금 그렇게하지 않으면 primary로 안넘어가나요..?

2020-11-26 13:39 UTC, plantstoen commented on src/button/icon-button/IconButton.tsx
> +  width: 4.5rem;
이부분 지워도 4.5rem으로 초기화되있어서 동작하지 않을까요..? 뭐 있어도 되지만 궁금해서요..!

2020-11-26 23:52 UTC, xodus0721 commented on src/button/basic-button/Button.stories.tsx
> +      <Button themeType="primary">
themeType 은 필수 타입이므로 안 적으면 빨간줄이 뜨더군요..

2020-11-26 23:53 UTC, xodus0721 commented on src/button/icon-button/IconButton.tsx
> +  width: 4.5rem;
디폴트값을 줘도 4.5rem 으로 동작하지 않습니다 ㅠㅠ

2020-11-27 05:07 UTC, plantstoen commented on src/button/basic-button/Button.stories.tsx
> +      <Button themeType="primary">
아아.... 알겠습니다 !

2020-11-27 05:07 UTC, plantstoen commented on src/button/icon-button/IconButton.tsx
> +  width: 4.5rem;
엥... 왜지 일단 알겠습니다...!

2020-11-27 05:08 UTC, merged